#%RAML 1.0 NamedExample
  [{
      movieID: 1,
      movieTitle: "Titanic",
      cinemaCode: "cin-01",
      startingTime: "10AM",
      endingTime: "12AM",
      movieType: "Romance"
    },
    {
      movieID: 2,
      movieTitle: "Avengers",
      cinemaCode: "cin-02",
      startingTime: "9AM",
      endingTime: "11AM",
      movieType: "Adventure"
    },
    {
      movieID: 3,
      movieTitle: "Avater",
      cinemaCode: "cin-01",
      startingTime: "10AM",
      endingTime: "12AM",
      movieType: "Sci-fi"
    }]